import { DEBUG, VisionEngine, geometry } from "./vision.js";

const APP_CONFIG = Object.freeze({ ANALYSIS_INTERVAL_MS: 180, MATCH_CONFIRMATIONS: 1, MATCH_HOLD_MS: 850, TRACK_DISTANCE_RATIO: 0.11, BOX_SMOOTHING: 0.56, CARD_REPLACEMENT_HISTOGRAM_SIMILARITY: 0.58 });
const video=document.querySelector("#camera"),overlay=document.querySelector("#overlay"),overlayContext=overlay.getContext("2d"),status=document.querySelector("#status"),retryButton=document.querySelector("#retry"),errorPanel=document.querySelector("#error");
const vision=new VisionEngine(),tracker=new MatchTracker(APP_CONFIG);let stream=null,analysisTimer=0,processing=false,lastResult=null,lastAnalysisStarted=0,analysesInWindow=0,analysisRate=0;
function attachCamera(mediaStream){stream=mediaStream||video.srcObject;if(!stream)return;errorPanel.hidden=true;retryButton.hidden=true;resizeOverlay();tracker.clear();setStatus("Analyzing…","analyzing");scheduleAnalysis(80)}
function stopCamera(){clearTimeout(analysisTimer);analysisTimer=0;if(stream){for(const t of stream.getTracks())t.stop();stream=null}if(video.srcObject)for(const t of video.srcObject.getTracks())t.stop();video.pause();video.srcObject=null}
function scheduleAnalysis(delay=APP_CONFIG.ANALYSIS_INTERVAL_MS){clearTimeout(analysisTimer);if(!stream||document.hidden)return;analysisTimer=setTimeout(runAnalysis,delay)}
function runAnalysis(){if(processing||!stream||video.readyState<HTMLMediaElement.HAVE_CURRENT_DATA||!video.videoWidth||!video.videoHeight){scheduleAnalysis(80);return}processing=true;const started=performance.now();try{const result=vision.analyze(video,overlay.clientWidth,overlay.clientHeight);if(result){lastResult=result;tracker.update(result,performance.now());updateAnalysisRate();updateStatus(result);drawOverlay()}}catch(e){console.error("Vision analysis failed",e);setStatus("Vision error","error")}finally{processing=false;scheduleAnalysis(Math.max(16,APP_CONFIG.ANALYSIS_INTERVAL_MS-(performance.now()-started)))}}
function updateAnalysisRate(){const now=performance.now();if(!lastAnalysisStarted)lastAnalysisStarted=now;analysesInWindow++;const elapsed=now-lastAnalysisStarted;if(elapsed>=1200){analysisRate=analysesInWindow*1000/elapsed;analysesInWindow=0;lastAnalysisStarted=now}}
function updateStatus(result){const visible=tracker.visible(performance.now());if(visible.length)setStatus(`Match ${visible.length}`,"match");else setStatus(`Analyzing · ${result.debug.candidateCount} objects · best ${result.debug.bestScore.toFixed(2)}`,"analyzing")}
function setStatus(text,state){status.hidden=false;if(status.textContent!==text)status.textContent=text;status.dataset.state=state}
function resizeOverlay(){const width=overlay.clientWidth,height=overlay.clientHeight,pixelRatio=Math.min(devicePixelRatio||1,3),tw=Math.round(width*pixelRatio),th=Math.round(height*pixelRatio),resized=overlay.width!==tw||overlay.height!==th;if(resized){overlay.width=tw;overlay.height=th}overlayContext.setTransform(pixelRatio,0,0,pixelRatio,0,0);if(resized)tracker.clear();drawOverlay()}
function drawOverlay(){const width=overlay.clientWidth,height=overlay.clientHeight;overlayContext.clearRect(0,0,width,height);if(!lastResult)return;for(const match of tracker.visible(performance.now())){drawMatchQuad(match.aQuad,match.frame);drawMatchQuad(match.bQuad,match.frame)}if(DEBUG)drawDebug(lastResult)}
function drawMatchQuad(quad,frame){const pts=quad.map(p=>analysisPointToDisplay(p,frame));overlayContext.lineJoin="round";overlayContext.beginPath();overlayContext.moveTo(pts[0].x,pts[0].y);for(let i=1;i<pts.length;i++)overlayContext.lineTo(pts[i].x,pts[i].y);overlayContext.closePath();overlayContext.strokeStyle="rgba(0,0,0,.82)";overlayContext.lineWidth=10;overlayContext.stroke();overlayContext.strokeStyle="#ff182b";overlayContext.lineWidth=6;overlayContext.stroke()}
function analysisPointToDisplay(point,frame){const videoX=frame.sourceRect.x+point.x*frame.sourceRect.width/frame.width,videoY=frame.sourceRect.y+point.y*frame.sourceRect.height/frame.height,cssWidth=overlay.clientWidth,cssHeight=overlay.clientHeight,coverScale=Math.max(cssWidth/frame.videoWidth,cssHeight/frame.videoHeight),offsetX=(cssWidth-frame.videoWidth*coverScale)*.5,offsetY=(cssHeight-frame.videoHeight*coverScale)*.5;return{x:offsetX+videoX*coverScale,y:offsetY+videoY*coverScale}}
function drawDebug(result){for(const c of result.candidates){const pts=c.quad.map(p=>analysisPointToDisplay(p,result.frame));overlayContext.beginPath();overlayContext.moveTo(pts[0].x,pts[0].y);for(let i=1;i<pts.length;i++)overlayContext.lineTo(pts[i].x,pts[i].y);overlayContext.closePath();overlayContext.strokeStyle="rgba(35,255,110,.65)";overlayContext.lineWidth=1;overlayContext.stroke()}const d=result.debug,lines=[`${d.processingMs.toFixed(0)} ms · ${analysisRate.toFixed(1)} Hz`,`${d.candidateCount} objects`, `best ${d.bestScore.toFixed(3)} · 2nd ${d.secondScore.toFixed(3)}`,`margin ${d.margin.toFixed(3)}`];overlayContext.font="12px ui-monospace,monospace";overlayContext.textBaseline="top";const pw=Math.max(...lines.map(l=>overlayContext.measureText(l).width))+16;overlayContext.fillStyle="rgba(0,0,0,.72)";overlayContext.fillRect(8,overlay.clientHeight-76,pw,68);overlayContext.fillStyle="#fff";lines.forEach((l,i)=>overlayContext.fillText(l,16,overlay.clientHeight-70+i*15))}
class MatchTracker{constructor(config){this.config=config;this.tracks=[]}clear(){this.tracks=[]}update(result,now){const unmatched=new Set(this.tracks);for(const match of result.matches){let closest=null,dist=Infinity;for(const t of unmatched){const d=matchDistance(t,match,result.frame);if(d<dist){closest=t;dist=d}}if(closest&&dist<=this.config.TRACK_DISTANCE_RATIO){const direct=quadCenterDistance(closest.aQuad,match.aQuad)+quadCenterDistance(closest.bQuad,match.bQuad),swapped=quadCenterDistance(closest.aQuad,match.bQuad)+quadCenterDistance(closest.bQuad,match.aQuad),a=swapped<direct?match.bQuad:match.aQuad,b=swapped<direct?match.aQuad:match.bQuad;closest.aQuad=smoothQuad(closest.aQuad,a,this.config.BOX_SMOOTHING);closest.bQuad=smoothQuad(closest.bQuad,b,this.config.BOX_SMOOTHING);closest.frame=result.frame;closest.score=match.score;closest.hits++;closest.lastSeen=now;closest.confirmed=closest.hits>=this.config.MATCH_CONFIRMATIONS;unmatched.delete(closest)}else this.tracks.push({aQuad:match.aQuad,bQuad:match.bQuad,frame:result.frame,score:match.score,hits:1,confirmed:this.config.MATCH_CONFIRMATIONS<=1,lastSeen:now})}this.tracks=this.tracks.filter(t=>now-t.lastSeen<=this.config.MATCH_HOLD_MS&&(t.confirmed||t.hits>0))}visible(now){return this.tracks.filter(t=>t.confirmed&&now-t.lastSeen<=this.config.MATCH_HOLD_MS)}}
function matchDistance(track,match,frame){const diag=Math.hypot(frame.width,frame.height),direct=quadCenterDistance(track.aQuad,match.aQuad)+quadCenterDistance(track.bQuad,match.bQuad),swapped=quadCenterDistance(track.aQuad,match.bQuad)+quadCenterDistance(track.bQuad,match.aQuad);return Math.min(direct,swapped)/(2*diag)}
function quadCenterDistance(a,b){const center=q=>q.reduce((s,p)=>({x:s.x+p.x/4,y:s.y+p.y/4}),{x:0,y:0}),ca=center(a),cb=center(b);return Math.hypot(ca.x-cb.x,ca.y-cb.y)}
function smoothQuad(prev,cur,w){return prev.map((p,i)=>({x:p.x*(1-w)+cur[i].x*w,y:p.y*(1-w)+cur[i].y*w}))}
window.addEventListener("dobble-camera-ready",e=>attachCamera(e.detail));window.addEventListener("resize",resizeOverlay,{passive:true});window.addEventListener("orientationchange",()=>setTimeout(resizeOverlay,180),{passive:true});document.addEventListener("visibilitychange",()=>{if(document.hidden)clearTimeout(analysisTimer);else if(stream){resizeOverlay();scheduleAnalysis(100)}});window.addEventListener("pagehide",stopCamera);if(video.srcObject?.active)attachCamera(video.srcObject);resizeOverlay();
if("serviceWorker" in navigator){navigator.serviceWorker.register("./sw.js",{updateViaCache:"none"}).then(r=>r.update()).catch(()=>{})}

export { attachCamera };