import { DEBUG, VisionEngine } from "./vision.js";
const APP_CONFIG={ANALYSIS_INTERVAL_MS:180,MATCH_HOLD_MS:1200};
const video=document.querySelector("#camera"),overlay=document.querySelector("#overlay"),ctx=overlay.getContext("2d"),status=document.querySelector("#status"),feedback=document.querySelector("#feedback"),retry=document.querySelector("#retry"),errorPanel=document.querySelector("#error");
const vision=new VisionEngine();let stream=null,timer=0,processing=false,lastResult=null,lastMatchAt=0;
function attachCamera(s){stream=s||video.srcObject;if(!stream)return;errorPanel.hidden=true;retry.hidden=true;resize();setStatus("Live analysis","analyzing");feedback.hidden=false;feedback.textContent="Point at two cards";schedule(60)}
function schedule(d=APP_CONFIG.ANALYSIS_INTERVAL_MS){clearTimeout(timer);if(stream&&!document.hidden)timer=setTimeout(runAnalysis,d)}
function runAnalysis(){if(processing||!stream||video.readyState<HTMLMediaElement.HAVE_CURRENT_DATA||!video.videoWidth){schedule(70);return}processing=true;const start=performance.now();try{const r=vision.analyze(video,overlay.clientWidth,overlay.clientHeight);if(r){lastResult=r;const ms=performance.now()-start;if(r.matches.length){lastMatchAt=performance.now();setStatus("MATCH FOUND","match");feedback.textContent=`${r.debug.candidateCount} symbols checked · ${(r.matches[0].score*100).toFixed(0)}% confidence`}else{setStatus("Scanning…","analyzing");feedback.textContent=r.debug.candidateCount<6?`Looking for symbols · ${r.debug.candidateCount} visible`:`${r.debug.candidateCount} symbols checked · best ${(r.debug.bestScore*100).toFixed(0)}%`}draw()}}catch(e){console.error(e);setStatus("Analyzer error","error");feedback.textContent=e&&e.message?e.message:"Vision analysis failed"}finally{processing=false;schedule(Math.max(20,APP_CONFIG.ANALYSIS_INTERVAL_MS-(performance.now()-start)))}}
function setStatus(t,s){status.hidden=false;status.textContent=t;status.dataset.state=s}
function resize(){const w=overlay.clientWidth,h=overlay.clientHeight,d=Math.min(devicePixelRatio||1,3);overlay.width=Math.round(w*d);overlay.height=Math.round(h*d);ctx.setTransform(d,0,0,d,0,0);draw()}
function point(p,f){const vx=f.sourceRect.x+p.x*f.sourceRect.width/f.width,vy=f.sourceRect.y+p.y*f.sourceRect.height/f.height,w=overlay.clientWidth,h=overlay.clientHeight,s=Math.max(w/f.videoWidth,h/f.videoHeight);return{x:(w-f.videoWidth*s)/2+vx*s,y:(h-f.videoHeight*s)/2+vy*s}}
function drawQuad(q,f){const p=q.map(x=>point(x,f));ctx.beginPath();ctx.moveTo(p[0].x,p[0].y);for(let i=1;i<p.length;i++)ctx.lineTo(p[i].x,p[i].y);ctx.closePath();ctx.lineJoin="round";ctx.strokeStyle="rgba(0,0,0,.85)";ctx.lineWidth=11;ctx.stroke();ctx.strokeStyle="#ff1738";ctx.lineWidth=6;ctx.stroke()}
function draw(){ctx.clearRect(0,0,overlay.clientWidth,overlay.clientHeight);if(!lastResult)return;if(lastResult.matches.length){for(const m of lastResult.matches){drawQuad(m.aQuad,lastResult.frame);drawQuad(m.bQuad,lastResult.frame)}}}
window.addEventListener("dobble-camera-ready",e=>attachCamera(e.detail));window.addEventListener("dobble-analyze-now",()=>{if(stream){clearTimeout(timer);runAnalysis()}});window.addEventListener("resize",resize,{passive:true});window.addEventListener("orientationchange",()=>setTimeout(resize,180),{passive:true});document.addEventListener("visibilitychange",()=>{if(document.hidden)clearTimeout(timer);else if(stream)schedule(50)});if(video.srcObject?.active)attachCamera(video.srcObject);resize();
if("serviceWorker" in navigator)navigator.serviceWorker.register("./sw.js",{updateViaCache:"none"}).then(r=>r.update()).catch(()=>{});
export{attachCamera};