export const DEBUG = false;
const CFG={EDGE:640,SIZE:40,ROT:24,MIN_AREA:6,MIN_BOX:.00012,MAX_BOX:.028,MAX_DIM:.22,MIN_SCORE:.50,STRONG_SCORE:.60,MAX_MATCHES:3};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export class VisionEngine{
 constructor(c={}){this.config={...CFG,...c};this.canvas=document.createElement('canvas');this.ctx=this.canvas.getContext('2d',{alpha:false,willReadFrequently:true});}
 analyze(video,vw,vh){const t=performance.now(),f=this.capture(video,vw,vh);if(!f)return null;const syms=segment(f.imageData,this.config);const cmp=compare(syms,f.width,f.height,this.config);return{frame:{width:f.width,height:f.height,videoWidth:f.videoWidth,videoHeight:f.videoHeight,sourceRect:f.sourceRect},cards:[],candidates:syms.map(s=>({quad:boxQuad(s.box)})),matches:cmp.accepted.map(p=>({score:p.score,margin:p.margin,aIndex:p.a,bIndex:p.b,aQuad:boxQuad(syms[p.a].box),bQuad:boxQuad(syms[p.b].box)})),state:cmp.accepted.length?'match':'searching',debug:{processingMs:performance.now()-t,candidateCount:syms.length,cardCount:0,symbolCounts:cmp.clusterSizes,bestScore:cmp.bestScore,secondScore:cmp.secondScore,margin:cmp.bestMargin}}}
 capture(video,vw,vh){const Vw=video.videoWidth,Vh=video.videoHeight;if(!Vw||!Vh||!vw||!vh)return null;const va=Vw/Vh,a=vw/vh;let sx=0,sy=0,sw=Vw,sh=Vh;if(a>va){sh=Vw/a;sy=(Vh-sh)/2}else{sw=Vh*a;sx=(Vw-sw)/2}let w,h;if(vw>=vh){w=this.config.EDGE;h=Math.max(1,Math.round(w/a))}else{h=this.config.EDGE;w=Math.max(1,Math.round(h*a))}if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h}this.ctx.drawImage(video,sx,sy,sw,sh,0,0,w,h);return{width:w,height:h,videoWidth:Vw,videoHeight:Vh,sourceRect:{x:sx,y:sy,width:sw,height:sh},imageData:this.ctx.getImageData(0,0,w,h)}}
}
function segment(img,c){const{width:w,height:h,data}=img,N=w*h;const mask=new Uint8Array(N);for(let i=0,p=0;i<N;i++,p+=4){const r=data[p],g=data[p+1],b=data[p+2],mx=Math.max(r,g,b),mn=Math.min(r,g,b),sat=mx?(mx-mn)/mx:0,v=mx/255; if((sat>.16&&v>.16)||v<.34)mask[i]=1}
 const comps=components(mask,w,h,c.MIN_AREA).filter(q=>{const ar=q.width*q.height/N;return ar>c.MIN_BOX*.05&&ar<c.MAX_BOX&&q.width<w*c.MAX_DIM&&q.height<h*c.MAX_DIM});
 const groups=group(comps,w,h);let out=[];for(const g of groups){const b=g.box,ar=b.width*b.height/N,asp=Math.max(b.width/b.height,b.height/b.width);if(ar<c.MIN_BOX||ar>c.MAX_BOX||b.width<7||b.height<7||asp>3.7)continue;const d=descriptor(img,mask,b,c);if(d.foregroundCount>=10&&ringBrightness(img,b)>.40)out.push(d)}
 // Remove nested/near-duplicate candidates, preferring the more compact box.
 out.sort((a,b)=>a.box.width*a.box.height-b.box.width*b.box.height);const keep=[];for(const s of out){if(keep.some(k=>iou(expand(k.box,3),s.box)>.62))continue;keep.push(s)}return keep.slice(0,36)}
function components(m,w,h,min){const seen=new Uint8Array(m.length),q=new Int32Array(m.length),o=[];for(let s=0;s<m.length;s++){if(!m[s]||seen[s])continue;let hd=0,tl=0,a=0,x0=w,y0=h,x1=0,y1=0;q[tl++]=s;seen[s]=1;while(hd<tl){const z=q[hd++],x=z%w,y=(z/w)|0;a++;x0=Math.min(x0,x);x1=Math.max(x1,x);y0=Math.min(y0,y);y1=Math.max(y1,y);if(x>0)add(z-1);if(x+1<w)add(z+1);if(y>0)add(z-w);if(y+1<h)add(z+w)}if(a>=min)o.push({area:a,minX:x0,minY:y0,maxX:x1,maxY:y1,width:x1-x0+1,height:y1-y0+1});function add(n){if(m[n]&&!seen[n]){seen[n]=1;q[tl++]=n}}}return o}
function group(cs,w,h){const p=cs.map((_,i)=>i),find=i=>{while(p[i]!==i){p[i]=p[p[i]];i=p[i]}return i},uni=(a,b)=>{a=find(a);b=find(b);if(a!==b)p[b]=a};const gap0=Math.max(3,Math.min(w,h)*.008);for(let a=0;a<cs.length;a++)for(let b=a+1;b<cs.length;b++){const A=cs[a],B=cs[b],gx=Math.max(0,Math.max(A.minX,B.minX)-Math.min(A.maxX,B.maxX)-1),gy=Math.max(0,Math.max(A.minY,B.minY)-Math.min(A.maxY,B.maxY)-1),gap=Math.hypot(gx,gy),cw=Math.max(A.maxX,B.maxX)-Math.min(A.minX,B.minX)+1,ch=Math.max(A.maxY,B.maxY)-Math.min(A.minY,B.minY)+1;if(gap<=gap0+Math.min(5,Math.sqrt(Math.min(A.area,B.area))*.18)&&cw<w*.115&&ch<h*.115)uni(a,b)}const mp=new Map;cs.forEach((x,i)=>{const r=find(i),g=mp.get(r)||{minX:w,minY:h,maxX:0,maxY:0,area:0};g.minX=Math.min(g.minX,x.minX);g.minY=Math.min(g.minY,x.minY);g.maxX=Math.max(g.maxX,x.maxX);g.maxY=Math.max(g.maxY,x.maxY);g.area+=x.area;mp.set(r,g)});return[...mp.values()].map(g=>({...g,box:{x:g.minX,y:g.minY,width:g.maxX-g.minX+1,height:g.maxY-g.minY+1}}))}
function descriptor(img,fg,b,c){const{width:w,data}=img;let sx=0,sy=0,n=0;for(let y=b.y;y<b.y+b.height;y++)for(let x=b.x;x<b.x+b.width;x++)if(fg[y*w+x]){sx+=x;sy+=y;n++}const cx=n?sx/n:b.x+b.width/2,cy=n?sy/n:b.y+b.height/2;let rad=1;for(let y=b.y;y<b.y+b.height;y++)for(let x=b.x;x<b.x+b.width;x++)if(fg[y*w+x])rad=Math.max(rad,Math.hypot(x-cx,y-cy));const S=c.SIZE,scale=rad/(S*.38),mask=new Uint8Array(S*S),color=new Uint8Array(S*S*3),hist=new Float32Array(12);let cnt=0;for(let y=0;y<S;y++)for(let x=0;x<S;x++){const px=Math.round(cx+(x-(S-1)/2)*scale),py=Math.round(cy+(y-(S-1)/2)*scale);if(px<0||py<0||px>=img.width||py>=img.height)continue;const si=py*w+px;if(!fg[si])continue;const j=y*S+x,k=si*4,r=data[k],g=data[k+1],bb=data[k+2],tot=r+g+bb+1;mask[j]=1;color[j*3]=r*255/tot;color[j*3+1]=g*255/tot;color[j*3+2]=bb*255/tot;const hsv=rgb2hsv(r,g,bb);hist[Math.min(11,(hsv.h*12)|0)]+=Math.max(.12,hsv.s);cnt++}const ht=hist.reduce((a,v)=>a+v,0)||1;for(let i=0;i<12;i++)hist[i]/=ht;const rots=[];for(let i=0;i<c.ROT;i++)rots.push(rotate(mask,color,S,i*Math.PI*2/c.ROT));return{box:b,mask,color,histogram:hist,foregroundCount:cnt,rotations:rots}}
function rotate(m,c,S,a){if(!a)return{mask:m,color:c,count:m.reduce((x,v)=>x+v,0)};const M=new Uint8Array(m.length),C=new Uint8Array(c.length),o=(S-1)/2,co=Math.cos(a),si=Math.sin(a);let n=0;for(let y=0;y<S;y++)for(let x=0;x<S;x++){const dx=x-o,dy=y-o,xx=Math.round(o+dx*co+dy*si),yy=Math.round(o-dx*si+dy*co);if(xx<0||yy<0||xx>=S||yy>=S)continue;const src=yy*S+xx;if(!m[src])continue;const d=y*S+x;M[d]=1;C[d*3]=c[src*3];C[d*3+1]=c[src*3+1];C[d*3+2]=c[src*3+2];n++}return{mask:M,color:C,count:n}}
function compare(ss,w,h,c){if(ss.length<2)return{accepted:[],bestScore:0,secondScore:0,bestMargin:0,clusterSizes:[ss.length,0]};const labels=splitTwo(ss,w,h),pairs=[];for(let a=0;a<ss.length;a++)for(let b=a+1;b<ss.length;b++){if(labels[a]===labels[b])continue;const score=sim(ss[a],ss[b]);pairs.push({a,b,score})}pairs.sort((a,b)=>b.score-a.score);for(const p of pairs){let alt=0;for(const q of pairs)if(q!==p&&(q.a===p.a||q.b===p.a||q.a===p.b||q.b===p.b))alt=Math.max(alt,q.score);p.margin=p.score-alt}const accepted=[];if(pairs[0]&&(pairs[0].score>=c.STRONG_SCORE||(pairs[0].score>=c.MIN_SCORE&&pairs[0].margin>=.012)))accepted.push(pairs[0]);return{accepted,bestScore:pairs[0]?.score||0,secondScore:pairs[1]?.score||0,bestMargin:pairs[0]?.margin||0,clusterSizes:[labels.filter(x=>x===0).length,labels.filter(x=>x===1).length]}}
function splitTwo(ss,w,h){const pts=ss.map(s=>center(s.box));let i0=0,i1=1,best=-1;for(let a=0;a<pts.length;a++)for(let b=a+1;b<pts.length;b++){const d=(pts[a].x-pts[b].x)**2+(pts[a].y-pts[b].y)**2;if(d>best){best=d;i0=a;i1=b}}let c0={...pts[i0]},c1={...pts[i1]},lab=[];for(let it=0;it<8;it++){lab=pts.map(p=>((p.x-c0.x)**2+(p.y-c0.y)**2)<=((p.x-c1.x)**2+(p.y-c1.y)**2)?0:1);for(const k of[0,1]){const a=pts.filter((_,i)=>lab[i]===k);if(a.length){const q={x:a.reduce((s,p)=>s+p.x,0)/a.length,y:a.reduce((s,p)=>s+p.y,0)/a.length};if(k===0)c0=q;else c1=q}}}return lab}
function sim(a,b){let hist=0;for(let i=0;i<12;i++)hist+=Math.min(a.histogram[i],b.histogram[i]);let best=0;for(const r of b.rotations){let inter=0,cd=0;for(let i=0;i<a.mask.length;i++){if(!a.mask[i]||!r.mask[i])continue;inter++;const k=i*3;cd+=Math.abs(a.color[k]-r.color[k])+Math.abs(a.color[k+1]-r.color[k+1])+Math.abs(a.color[k+2]-r.color[k+2])}if(!inter)continue;const dice=2*inter/Math.max(1,a.foregroundCount+r.count),col=clamp(1-cd/(inter*275),0,1),cov=inter/Math.max(1,Math.min(a.foregroundCount,r.count));best=Math.max(best,dice*.48+col*.22+hist*.20+cov*.10)}return best}
function ringBrightness(img,b){const{width:w,height:h,data}=img,p=Math.max(4,Math.round(Math.min(b.width,b.height)*.35)),x0=Math.max(0,b.x-p),y0=Math.max(0,b.y-p),x1=Math.min(w,b.x+b.width+p),y1=Math.min(h,b.y+b.height+p);let s=0,n=0;for(let y=y0;y<y1;y+=3)for(let x=x0;x<x1;x+=3){if(x>=b.x&&x<b.x+b.width&&y>=b.y&&y<b.y+b.height)continue;const k=(y*w+x)*4;s+=Math.max(data[k],data[k+1],data[k+2])/255;n++}return n?s/n:0}
function rgb2hsv(r,g,b){r/=255;g/=255;b/=255;const mx=Math.max(r,g,b),mn=Math.min(r,g,b),d=mx-mn;let h=0;if(d){if(mx===r)h=((g-b)/d)%6;else if(mx===g)h=(b-r)/d+2;else h=(r-g)/d+4;h/=6;if(h<0)h++}return{h,s:mx?d/mx:0}}
function center(b){return{x:b.x+b.width/2,y:b.y+b.height/2}}function expand(b,p){return{x:b.x-p,y:b.y-p,width:b.width+2*p,height:b.height+2*p}}function iou(a,b){const l=Math.max(a.x,b.x),t=Math.max(a.y,b.y),r=Math.min(a.x+a.width,b.x+b.width),d=Math.min(a.y+a.height,b.y+b.height),I=Math.max(0,r-l)*Math.max(0,d-t);return I/Math.max(1,a.width*a.height+b.width*b.height-I)}
function boxQuad(b){const p=Math.max(4,Math.min(b.width,b.height)*.18);return[{x:b.x-p,y:b.y-p},{x:b.x+b.width+p,y:b.y-p},{x:b.x+b.width+p,y:b.y+b.height+p},{x:b.x-p,y:b.y+b.height+p}]}
function quadBounds(q){const xs=q.map(p=>p.x),ys=q.map(p=>p.y),x=Math.min(...xs),y=Math.min(...ys);return{x,y,width:Math.max(...xs)-x,height:Math.max(...ys)-y}}function boxIoU(a,b){return iou(a,b)}function projectPoint(t,u,v){const d=t?.g*u+t?.h*v+1||1;return{x:((t?.a||0)*u+(t?.b||0)*v+(t?.c||0))/d,y:((t?.d||0)*u+(t?.e||0)*v+(t?.f||0))/d}}
export const geometry={projectPoint,quadBounds,boxIoU};
